### ISSUE TITLE
rclone_sa.json can not be in another directory

### ISSUE THREAD

**Issue by christophedc0** [MrZablah/SyncPosterProcess#7]
In the config file we have:
```gdrive_sa_location``` set to ```/config/rclone_sa.json``` by default.
I however wanted to put it in ```/config/rclone/rclone_sa.json``` but the script always seemed to use the default location and not the one configured in the config.yml

```2023/12/15 09:59:20 Failed to create file system for "posters:": drive: failed when making oauth client: error opening service account credentials file: open /config/rclone_sa.json: no such file or directory```

Moving the file to the default location works fine.

**Comment by MrZablah** [comment]
Thanks for this I will look into this
