### ISSUE TITLE
does not start for me

### ISSUE THREAD

**Issue by sahara101** [MrZablah/SyncPosterProcess#8]
Hi, I am getting this in the log:

Running sync_gdrive
Sync list: [1]
Syncing: 1
No sync location provided

Can you maybe help me please? The docker mount is OK, no idea what to do.

Thanks!

**Comment by MrZablah** [comment]
can you show me your config file?

**Comment by sahara101** [comment]
Hey! sorry for late reply, but it is working now, so all good. Thanks :)
