### ISSUE TITLE
Error when starting the container

### ISSUE THREAD

**Issue by TheDestr0yer** [MrZablah/SyncPosterProcess#9]
Hi I noticed that it is a couple of days that SPP gives me this error as soon as it is started , before everything worked normally and I did not touch anything
```UnboundLocalError: cannot access local variable 'github_script_version' where it is not associated with a value
usermod: no changes
Traceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    from modules import sync_gdrive, renamer, fix_border, unmatched_assets
  File "/app/modules/renamer.py", line 36, in <module>
    version(config.script_name, script_version, arrpy_py_version, logger, config)
  File "/app/utility/version.py", line 31, in version
    github_script_version_int = int(github_script_version.replace(".", ""))
                                    ^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'github_script_version' where it is not associated with a value```

**Comment by Elbulus** [comment]
This is most likely due to  Drazzilb08 renaming the userscripts repository that the scripts would check to make sure the versions were upto date. 

The reason for this because the below has replaced userscripts which also does the same as SPP and more. 
https://github.com/Drazzilb08/daps/tree/master

**Comment by MrZablah** [comment]
Yes because of this we have mark this repo as deprecated and will now suggest to use this instead:
https://github.com/Drazzilb08/daps/wiki
